In [2]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

In [3]:
from sqlalchemy import create_engine

username = "root"
password = "1779"
host = "localhost"
database = "olist_ecommerce_db"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}/{database}"
)

print("✅ Database Connected Successfully!")

✅ Database Connected Successfully!

In [4]:
customers = pd.read_sql("SELECT * FROM customers", engine)
orders = pd.read_sql("SELECT * FROM orders", engine)
payments = pd.read_sql("SELECT * FROM payments", engine)
order_items = pd.read_sql("SELECT * FROM order_items", engine)
products = pd.read_sql("SELECT * FROM products", engine)
reviews = pd.read_sql("SELECT * FROM order_reviews", engine)
sellers = pd.read_sql("SELECT * FROM sellers", engine)
category = pd.read_sql("SELECT * FROM category_translation", engine)

print("✅ All tables loaded successfully!")

✅ All tables loaded successfully!

In [5]:
print("Customers :", customers.shape)
print("Orders :", orders.shape)
print("Payments :", payments.shape)
print("Order Items :", order_items.shape)
print("Products :", products.shape)
print("Reviews :", reviews.shape)
print("Sellers :", sellers.shape)
print("Category :", category.shape)

Customers : (99441, 5)
Orders : (99441, 8)
Payments : (103886, 5)
Order Items : (112650, 7)
Products : (32951, 9)
Reviews : (99224, 7)
Sellers : (3095, 4)
Category : (71, 2)

In [6]:
master_df = orders.merge(
    customers,
    on="customer_id",
    how="left"
)

print(master_df.shape)
master_df.head()

(99441, 12)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [8]:
master_df = master_df.merge(
    payments,
    on="order_id",
    how="left"
)

print(master_df.shape)
master_df.head()

(103887, 16)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,1.0,credit_card,1.0,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,3.0,voucher,1.0,2.00
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,2.0,voucher,1.0,18.59
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,1.0,boleto,1.0,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,1.0,credit_card,3.0,179.12

In [9]:
payments['order_id'].nunique()

99440

In [10]:
payments.shape

(103886, 5)

In [11]:
master_df = master_df.merge(
    reviews,
    on="order_id",
    how="left"
)

print(master_df.shape)
master_df.head()

(104478, 22)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,1.0,boleto,1.0,141.46,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,1.0,credit_card,3.0,179.12,e73b67b67587f7644d5bd1a52deb1b01,5.0,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58

In [12]:
master_df = master_df.merge(
    order_items,
    on="order_id",
    how="left"
)

print(master_df.shape)
master_df.head()

(119143, 28)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50,1.0,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58,1.0,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22

In [13]:
master_df = master_df.merge(
    products,
    on="product_id",
    how="left"
)

print(master_df.shape)

(119143, 36)

In [14]:
master_df = master_df.merge(
    category,
    on="product_category_name",
    how="left"
)

print(master_df.shape)

(119143, 37)

In [16]:
master_df = master_df.merge(
    sellers,
    on="seller_id",
    how="left"
)

print(master_df.shape)

(119143, 43)

In [17]:
master_df.shape

(119143, 43)

In [18]:
# Master Dataset Validation
master_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 43 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  str
 1   customer_id                    119143 non-null  str
 2   order_status                   119143 non-null  str
 3   order_purchase_timestamp       119143 non-null  str
 4   order_approved_at              118966 non-null  str
 5   order_delivered_carrier_date   117057 non-null  str
 6   order_delivered_customer_date  115722 non-null  str
 7   order_estimated_delivery_date  119143 non-null  str
 8   customer_unique_id             119143 non-null  str
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  str
 11  customer_state                 119143 non-null  str
 12  payment_sequential             119140 non-null  float64
 13  payment_type                   119140 non-null  str
 14  payment_installments           119140 non-null  float64
 15  payment_value                  119140 non-null  float64
 16  review_id                      118146 non-null  str
 17  review_score                   118146 non-null  float64
 18  review_comment_title           13989 non-null   str
 19  review_comment_message         50245 non-null   str
 20  review_creation_date           118146 non-null  str
 21  review_answer_timestamp        118146 non-null  str
 22  order_item_id                  118310 non-null  float64
 23  product_id                     118310 non-null  str
 24  seller_id                      118310 non-null  str
 25  shipping_limit_date            118310 non-null  str
 26  price                          118310 non-null  float64
 27  freight_value                  118310 non-null  float64
 28  product_category_name          116601 non-null  str
 29  product_name_lenght            116601 non-null  float64
 30  product_description_lenght     116601 non-null  float64
 31  product_photos_qty             116601 non-null  float64
 32  product_weight_g               118290 non-null  float64
 33  product_length_cm              118290 non-null  float64
 34  product_height_cm              118290 non-null  float64
 35  product_width_cm               118290 non-null  float64
 36  product_category_name_english  116576 non-null  str
 37  seller_zip_code_prefix_x       118310 non-null  float64
 38  seller_city_x                  118310 non-null  str
 39  seller_state_x                 118310 non-null  str
 40  seller_zip_code_prefix_y       118310 non-null  float64
 41  seller_city_y                  118310 non-null  str
 42  seller_state_y                 118310 non-null  str
dtypes: float64(16), int64(1), str(26)
memory usage: 91.3 MB

In [19]:
master_df.shape

(119143, 43)

In [20]:
master_df.isnull().sum().sort_values(ascending=False)

review_comment_title             105154
review_comment_message            68898
order_delivered_customer_date      3421
product_category_name_english      2567
product_category_name              2542
product_description_lenght         2542
product_name_lenght                2542
product_photos_qty                 2542
order_delivered_carrier_date       2086
review_score                        997
review_creation_date                997
review_id                           997
review_answer_timestamp             997
product_weight_g                    853
product_length_cm                   853
product_width_cm                    853
product_height_cm                   853
product_id                          833
shipping_limit_date                 833
seller_city_y                       833
freight_value                       833
seller_zip_code_prefix_x            833
seller_city_x                       833
seller_state_x                      833
price                               833
seller_id                           833
order_item_id                       833
seller_state_y                      833
seller_zip_code_prefix_y            833
order_approved_at                   177
payment_sequential                    3
payment_value                         3
payment_type                          3
payment_installments                  3
order_status                          0
customer_city                         0
customer_zip_code_prefix              0
customer_unique_id                    0
order_estimated_delivery_date         0
order_purchase_timestamp              0
order_id                              0
customer_id                           0
customer_state                        0
dtype: int64

In [21]:
master_df.duplicated().sum()

np.int64(0)

In [22]:
master_df.dtypes

order_id                             str
customer_id                          str
order_status                         str
order_purchase_timestamp             str
order_approved_at                    str
order_delivered_carrier_date         str
order_delivered_customer_date        str
order_estimated_delivery_date        str
customer_unique_id                   str
customer_zip_code_prefix           int64
customer_city                        str
customer_state                       str
payment_sequential               float64
payment_type                         str
payment_installments             float64
payment_value                    float64
review_id                            str
review_score                     float64
review_comment_title                 str
review_comment_message               str
review_creation_date                 str
review_answer_timestamp              str
order_item_id                    float64
product_id                           str
seller_id                            str
shipping_limit_date                  str
price                            float64
freight_value                    float64
product_category_name                str
product_name_lenght              float64
product_description_lenght       float64
product_photos_qty               float64
product_weight_g                 float64
product_length_cm                float64
product_height_cm                float64
product_width_cm                 float64
product_category_name_english        str
seller_zip_code_prefix_x         float64
seller_city_x                        str
seller_state_x                       str
seller_zip_code_prefix_y         float64
seller_city_y                        str
seller_state_y                       str
dtype: object

In [23]:
master_df.describe()

,customer_zip_code_prefix,payment_sequential,payment_installments,payment_value,review_score,order_item_id,price,freight_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix_x,seller_zip_code_prefix_y
count,119143.000000,119140.000000,119140.000000,119140.000000,118146.000000,118310.000000,118310.000000,118310.000000,116601.000000,116601.000000,116601.000000,118290.000000,118290.000000,118290.000000,118290.000000,118310.000000,118310.000000
mean,35033.451298,1.094737,2.941246,172.735135,4.015582,1.196543,120.646603,20.032387,48.767498,785.967822,2.205161,2112.250740,30.265145,16.619706,23.074799,24442.410413,24442.410413
std,29823.198969,0.730141,2.777848,267.776077,1.400436,0.699489,184.109691,15.836850,10.033540,652.584121,1.717452,3786.695111,16.189367,13.453584,11.749139,27573.004511,27573.004511
min,1003.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.850000,0.000000,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000,1001.000000,1001.000000
25%,11250.000000,1.000000,1.000000,60.850000,4.000000,1.000000,39.900000,13.080000,42.000000,346.000000,1.000000,300.000000,18.000000,8.000000,15.000000,6429.000000,6429.000000
50%,24240.000000,1.000000,2.000000,108.160000,5.000000,1.000000,74.900000,16.280000,52.000000,600.000000,1.000000,700.000000,25.000000,13.000000,20.000000,13660.000000,13660.000000
75%,58475.000000,1.000000,4.000000,189.240000,5.000000,1.000000,134.900000,21.180000,57.000000,983.000000,3.000000,1800.000000,38.000000,20.000000,30.000000,27972.000000,27972.000000
max,99990.000000,29.000000,24.000000,13664.080000,5.000000,21.000000,6735.000000,409.680000,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000,99730.000000,99730.000000

In [24]:
master_df.nunique().sort_values(ascending=False)

order_id                         99441
customer_id                      99441
order_purchase_timestamp         98875
review_id                        98410
review_answer_timestamp          98248
customer_unique_id               96096
order_delivered_customer_date    95664
shipping_limit_date              93318
order_approved_at                90733
order_delivered_carrier_date     81018
review_comment_message           36159
product_id                       32951
payment_value                    29077
customer_zip_code_prefix         14994
freight_value                     6999
price                             5968
review_comment_title              4527
customer_city                     4119
seller_id                         3095
product_description_lenght        2960
seller_zip_code_prefix_y          2246
seller_zip_code_prefix_x          2246
product_weight_g                  2204
review_creation_date               636
seller_city_y                      611
seller_city_x                      611
order_estimated_delivery_date      459
product_height_cm                  102
product_length_cm                   99
product_width_cm                    95
product_category_name               73
product_category_name_english       71
product_name_lenght                 66
payment_sequential                  29
customer_state                      27
payment_installments                24
seller_state_y                      23
seller_state_x                      23
order_item_id                       21
product_photos_qty                  19
order_status                         8
payment_type                         5
review_score                         5
dtype: int64